# PTools Python Library Makefile
# Author: Generated by GitHub Copilot
# Description: Build, test, lint, and development tasks for the PTools library

.PHONY: help install install-dev clean clean-all build test test-verbose lint format check-format check deps update venv docs publish publish-test

# Default target
.DEFAULT_GOAL := help

# Colors for output
BLUE := \033[36m
GREEN := \033[32m
YELLOW := \033[33m
RED := \033[31m
RESET := \033[0m

# Configuration
PACKAGE_NAME := ptools
PYTHON_VERSION := 3.11
VENV_NAME := .venv
TEST_PATH := tests/
SRC_PATH := ptools/

# Command shortcuts
UV := uv
RUFF := uv run ruff
PYTEST := uv run pytest


help: ## Show this help message
	@echo "$(BLUE)PTools Python Library$(RESET)"
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  $(GREEN)%-20s$(RESET) %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# Environment setup
venv: ## Create a virtual environment using uv
	@echo "$(BLUE)Creating virtual environment...$(RESET)"
	$(UV) venv $(VENV_NAME) --python $(PYTHON_VERSION)
	@echo "$(GREEN)Virtual environment created. Activate with: source $(VENV_NAME)/bin/activate$(RESET)"

install: ## Install package dependencies
	@echo "$(BLUE)Installing dependencies...$(RESET)"
	$(UV) pip install -e .
	@echo "$(GREEN)Dependencies installed$(RESET)"

install-dev: ## Install package with development dependencies
	@echo "$(BLUE)Installing development dependencies...$(RESET)"
	$(UV) pip install -e ".[test,dev]"
	@echo "$(GREEN)Development dependencies installed$(RESET)"

deps: ## Update and sync dependencies
	@echo "$(BLUE)Updating dependencies...$(RESET)"
	$(UV) lock
	$(UV) sync
	@echo "$(GREEN)Dependencies updated$(RESET)"

# Build tasks
build: clean ## Build the package
	@echo "$(BLUE)Building package...$(RESET)"
	$(UV) build
	@echo "$(GREEN)Package built successfully$(RESET)"

# Cleaning tasks
clean: ## Clean build artifacts
	@echo "$(BLUE)Cleaning build artifacts...$(RESET)"
	rm -rf build/
	rm -rf dist/
	rm -rf *.egg-info/
	rm -rf .pytest_cache/
	find . -type d -name __pycache__ -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	find . -type f -name "*.pyo" -delete
	@echo "$(GREEN)Build artifacts cleaned$(RESET)"

clean-all: clean ## Clean all artifacts including virtual environment
	@echo "$(BLUE)Cleaning all artifacts...$(RESET)"
	rm -rf $(VENV_NAME)/
	rm -rf .coverage
	rm -rf htmlcov/
	rm -rf .ruff_cache/
	@echo "$(GREEN)All artifacts cleaned$(RESET)"

# Testing tasks
test: ## Run tests with pytest
	@echo "$(BLUE)Running tests...$(RESET)"
	$(PYTEST) $(TEST_PATH)
	@echo "$(GREEN)Tests completed$(RESET)"

test-verbose: ## Run tests with verbose output
	@echo "$(BLUE)Running tests with verbose output...$(RESET)"
	$(PYTEST) $(TEST_PATH) -v -s --tb=long
	@echo "$(GREEN)Tests completed$(RESET)"

# Code quality tasks
lint-check: ## Check if code is properly formatted
	@echo "$(BLUE)Running linter...$(RESET)"
	$(RUFF) check $(SRC_PATH) $(TEST_PATH)
	@echo "$(GREEN)Linting completed$(RESET)"

lint-format: ## Format code with ruff
	@echo "$(BLUE)Formatting code...$(RESET)"
	$(RUFF) format $(SRC_PATH) $(TEST_PATH)
	$(RUFF) check $(SRC_PATH) $(TEST_PATH) --fix
	@echo "$(GREEN)Code formatted$(RESET)"

# Package management
update: ## Update all dependencies to latest versions
	@echo "$(BLUE)Updating dependencies...$(RESET)"
	$(UV) lock --upgrade
	$(UV) sync
	@echo "$(GREEN)Dependencies updated$(RESET)"

# Show project info
info: ## Show project information
	@echo "$(BLUE)Project Information:$(RESET)"
	@echo "  Name: $(PACKAGE_NAME)"
	@echo "  Python Version: $(PYTHON_VERSION)"
	@echo "  Virtual Environment: $(VENV_NAME)"
	@echo "  Source Path: $(SRC_PATH)"
	@echo "  Test Path: $(TEST_PATH)"
	@echo ""
	@echo "$(BLUE)Quick Start:$(RESET)"
	@echo "  1. make dev-setup"
	@echo "  2. source $(VENV_NAME)/bin/activate"
	@echo "  3. make dev-check"
