[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ptools"
description = "New PTools: a fully pythonic PTools"
readme = "README.rst"
requires-python = ">=3.11.0"
keywords = ["ptools"]
license = {text = "MIT"}
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
]
dependencies = [

]
dynamic = ["version"]

[project.scripts]
ptools-script = "ptools.cli.ptools_cli:main"
